function  f=singlesd2(x,t,c,a)

 f=3*c*c*sqrt(c)/16*sech(sqrt(c)/2*(x-c*t-a))*sech(sqrt(c)/2*(x-c*t-a))*sech(sqrt(c)/2*(x-c*t-a))*...
     sech(sqrt(c)/2*(x-c*t-a))*sech(sqrt(c)/2*(x-c*t-a))*(exp(-sqrt(c)/2*(x-c*t-a))-exp(sqrt(c)/2*(x-c*t-a)))*...
     (exp(-sqrt(c)/2*(x-c*t-a))-exp(sqrt(c)/2*(x-c*t-a)))*(exp(-sqrt(c)/2*(x-c*t-a))-exp(sqrt(c)/2*(x-c*t-a)))-...
     3*c*c*sqrt(c)/16*sech(sqrt(c)/2*(x-c*t-a))*sech(sqrt(c)/2*(x-c*t-a))*sech(sqrt(c)/2*(x-c*t-a))*...
     sech(sqrt(c)/2*(x-c*t-a))*(exp(-sqrt(c)/2*(x-c*t-a))-exp(sqrt(c)/2*(x-c*t-a)))*...
     (exp(-sqrt(c)/2*(x-c*t-a))+exp(sqrt(c)/2*(x-c*t-a)))-...
     3*c*c*sqrt(c)/32*sech(sqrt(c)/2*(x-c*t-a))*sech(sqrt(c)/2*(x-c*t-a))*sech(sqrt(c)/2*(x-c*t-a))*...
     sech(sqrt(c)/2*(x-c*t-a))*(exp(-sqrt(c)/2*(x-c*t-a))+exp(sqrt(c)/2*(x-c*t-a)))*...
     (exp(-sqrt(c)/2*(x-c*t-a))-exp(sqrt(c)/2*(x-c*t-a)))-...
      c*c*sqrt(c)/16*sech(sqrt(c)/2*(x-c*t-a))*sech(sqrt(c)/2*(x-c*t-a))*sech(sqrt(c)/2*(x-c*t-a))*...
     (-exp(-sqrt(c)/2*(x-c*t-a))+exp(sqrt(c)/2*(x-c*t-a)));