function  f=singlesd1(x,t,c,a)

 f=3*c*c/16*sech(sqrt(c)/2*(x-c*t-a))*sech(sqrt(c)/2*(x-c*t-a))*sech(sqrt(c)/2*(x-c*t-a))*...
     sech(sqrt(c)/2*(x-c*t-a))*(exp(-sqrt(c)/2*(x-c*t-a))-exp(sqrt(c)/2*(x-c*t-a)))*...
     (exp(-sqrt(c)/2*(x-c*t-a))-exp(sqrt(c)/2*(x-c*t-a)))-...
     c*c/8*sech(sqrt(c)/2*(x-c*t-a))*sech(sqrt(c)/2*(x-c*t-a))*sech(sqrt(c)/2*(x-c*t-a))*...
     (exp(-sqrt(c)/2*(x-c*t-a))+exp(sqrt(c)/2*(x-c*t-a)));

